### ISSUE TITLE
Do not explicitly search for a library file name

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess-ModbusBackend#1]
You are searching for libmodbus.so.5 explicitly. This will fail on systems which have a different version of the library, even if it is still compatible. There is no need to do so, since the dev package comes with a symlink, so the library is found by libmodmus.so as well.

**Comment by zenker** [comment]
OK I did not check that so far. So libmodbus-dev installs the package libmodbus5 and sets the symlink.
