### ISSUE TITLE
Adapt to changes in DeviceAccess

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess-ModbusBackend#4]
Depends on ChimeraTK/DeviceAccess#117, ChimeraTK/DeviceAccess#116 and ChimeraTK/DeviceAccess#119

Adapt to the changes in DeviceAccess:

*    ChimeraTK/DeviceAccess#116 and ChimeraTK/DeviceAccess#119 introduce API-breaking changes to pre/postRead/Write. Add the new arguments to the function overloads. Check Whether the functions should be used (for instance don't generate a new version number in postRead if readTransferLatest did not get new data)
*    ChimeraTK/DeviceAccess#117 introduces readTransfer() etc (non-overloaded functions without "do"). Use them whenever delegating or using a transfer (applies for all 6 read and write transfer functions)

**Comment by mhier** [comment]
done a while ago already
